### ISSUE TITLE
Library needs formal documentation

### ISSUE THREAD

**Issue by Nerdietony** [rkuykendall/marvelous#1]
Can i see your docs?

**Comment by rkuykendall** [comment]
Here's [a repository with three scripts that use this library](https://github.com/rkuykendall/marvel-scripts). Currently the formal documentation is in the early staged at http://marvelous.readthedocs.io/en/latest/, and I will update this issue with progress in the next week.

**Comment by rkuykendall** [comment]
Hey @Nerdietony, with the 1.0.0 release, you can now find full documentation at http://marvelous.readthedocs.io/en/latest/

Let me know if there's anything that could use improvement.
